version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
    image: subwayroad:0.1
    ports:
      - 8080:8080