version: '3'

services:

  app:
    build:
      dockerfile: Dockerfile
      context: ./target/docker/stage/
    ports:
      - "8000:8000"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "8001:5432"